[package]
name = "round-based"
version = "0.2.0"
edition = "2018"
license = "GPL-3.0"
description = "Driver for MPC protocols"
repository = "https://github.com/ZenGo-X/round-based-protocol"
categories = ["asynchronous", "cryptography", "network-programming"]
keywords = ["round-based", "mpc", "protocol"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
phantom-type = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
pin-project-lite = "0.2"
async-stream = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
round-based-derive = { path = "../round-based-derive", optional = true }

# tls support
rustls = { version = "0.19", features = ["dangerous_configuration"], optional = true }
webpki = { version = "0.21", optional = true }
tokio-rustls = { version = "0.22", optional = true }

[dev-dependencies]
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.9"
hex = "*"
trybuild = "1"
rcgen = "0.8"

[features]
default = ["tls"]
derive = ["round-based-derive"]
tls = ["rustls", "webpki", "tokio-rustls"]

[[example]]
name = "mpc_random_generation"
required-features = ["derive"]

[[test]]
name = "derive"
required-features = ["derive"]
